name: Android Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        api-level: [26, 29]
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedDebugAndroidTest --debug