name: Android Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        api-level: [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: avdmanager list

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: pixel_3a
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck